# Generated by Django 3.2 on 2023-01-21 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_mark_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='author',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='mark',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.mark'),
            preserve_default=False,
        ),
    ]
