# Generated by Django 3.2 on 2023-01-21 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20230121_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='mark_value',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
