# Generated by Django 3.2 on 2023-01-21 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_author_is_staff'),
        ('posts', '0002_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.author'),
            preserve_default=False,
        ),
    ]
