# Generated by Django 3.2 on 2023-01-21 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_mark_mark_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mark',
        ),
    ]
